title: Maël Code base
description: My Personal Code base
author: Maël Vincent
github: https://github.com/mvkirk
about: I am freelance developer. I work on all the stack and currently more with Angular 1/2, Python and Ruby
disqus_shortname: mvkirk-github-io
google_analytics: UA-85216585-3

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/mv_kirk"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/mael-vincent"
    - icon: fa-stack-exchange
      link: "http://stackexchange.com/users/3641204/ma%C3%ABl"

share:
  twitter_username: mv_kirk

urls:
    - text: About Me
      url: /about/
    - text: Github
      url: https://github.com/mvkirk
    - text: XML Feed
      url: /feed.xml

url: "https://mvkirk.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
